/*
Version of OS - Ubuntu 18.04.3 LTS
IDE - Visual Studio Code for C++
Compiler- g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Linker - g++
Image Viewing Software - ImageJ (http://rsb.info.nih.gov/ij/)

Copyright © 2020 Yogesh Gajjar. All rights reserved.


STEPS TO RUN THE CODE 
1.  Open terminal and change the directory where the source code files are downloaded. 
2.  Compile the codes using: "g++ sourcecode.cpp -o output" 
3.  Run and execute the code and then write "./output height width train_read
4.  This will run the training images and write the feature vectors into a file called "featurevector_class.txt" 
5.  Follow the steps mentioned in the terminal. It says to run the next mode "test_read". Write in terminal "./output 128 128 test_read"
6.  After that, follow the commands mentioned in the terminal. 
7.  While executing the program in MATLAB, please mention the working directory where this program is saved. 
*/ 

#include <opencv2/core/utility.hpp>
#include <opencv2/core.hpp>
#include <iostream>
#include <algorithm> 
#include <vector>
#include <string>
#include <sstream>
#include <cmath>
#include <math.h>
#include <fstream> 
#include "texture_classification.h"

using namespace std;
using namespace cv;

int main(int argc, char *argv[]) {
    int height{atoi(argv[1])}, width{atoi(argv[2])}, trainCount{36}, testCount{12}; 
    string choice{argv[3]};
    Classification *feature = new Classification(height, width, 5);

    if (choice == "train_read") {
        cout << "\n[INFO] Train Read Mode: " << endl;
        feature->calculateEnergy(1, trainCount);
        feature->convert25Dto15D(trainCount);
        feature->computePCA(trainCount, choice);
        cout << "Now run the next mode i.e. test_read" << endl;
    }
    
    if(choice == "test_read") {
        cout << "Test Read Mode: " << endl;
        feature->calculateEnergy(0, testCount);
        feature->convert25Dto15D(testCount);
        feature->computePCA(testCount, choice);    
        cout << "[INFO] Step 1: Open MATLAB and run the file classification.m present in the working directory. That file will read the .txt generated by this program and will perform PCA for both train and test images.\n" << endl;
        cout << "[INFO] Step 2: After executing the classification.m file in MATLAB, also execute the classification_test.m file to perform PCA for KMeans unsupervised learning classification." <<
                         "Also ensure the working directory is same while entering it in the MATLAB file.\n" << endl;
        cout << "[INFO] Step 3: After executing the all MATLAB files, run the next mode i.e test_PCA.\n" << endl;   
    }
    
    if(choice == "test_PCA") {
        cout << "Test PCA mode: " << endl;
        feature->calculateEnergy(0, testCount);
        feature->convert25Dto15D(testCount);
        feature->computePCA(testCount, choice);
        feature->kMeans15D(15);
        feature->kMeans3D(3);
    }

    feature->deleteAll();
    delete feature;
    return 0;
}
